ROOT_DIR              =..
SRC_DIR               =.
VENDOR_SRC            =$(SRC_DIR)/vendor/$(VENDOR)
VENDOR_FAMILY_SRC	  =$(VENDOR_SRC)/$(FAMILY)
VENDOR_FAMILY_DEVICE  =$(VENDOR_FAMILY_SRC)/device
VENDOR_DEVICE_SRC	  =$(VENDOR_FAMILY_SRC)/$(DEVICE)
VENDOR_DEVICE_BOARD	  =$(VENDOR_DEVICE_SRC)/$(BOARD)
DEVICE_DEVICE_SRC	  =$(VENDOR_DEVICE_SRC)/device
VENDOR_DEVICE_GCC_SRC =$(DEVICE_DEVICE_SRC)/TOOLCHAIN_GCC_ARM

CMSIS				  =$(SRC_DIR)/cmsis
CMSIS_TARGET_CORTEX_M =$(SRC_DIR)/cmsis/TARGET_CORTEX_M
MBED_CAPI_SRC         =$(SRC_DIR)/capi
MBED_CPP_SRC          =$(SRC_DIR)/cpp

DROP_DIR              =$(ROOT_DIR)/drop

DEVICE_DROP           =$(DROP_DIR)/$(DEVICE)

RELEASE_DROP          =$(DEVICE_DROP)/GCC_ARM
DEBUG_DROP            =$(DEVICE_DROP)/GCC_ARM/Debug

RELEASE_OBJDIR        =$(SRC_DIR)/Release/$(DEVICE)
DEBUG_OBJDIR          =$(SRC_DIR)/Debug/$(DEVICE)

#VENDOR_CAPI_SRC       =$(VENDOR_SRC)/capi
#VENDOR_CAPI_DEVICE_SRC=$(VENDOR_CAPI_SRC)/$(DEVICE)
#VENDOR_CMSIS_SRC      =$(VENDOR_SRC)/cmsis/$(DEVICE)
#VENDOR_CMSIS_GCC_SRC  =$(VENDOR_CMSIS_SRC)/GCC_ARM
